### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by Fuku-Taka** [Fuku-Taka/free_merge#48]
■ URL
IPアドレス：http://54.248.243.225
Github（最終課題のリポジトリ）：https://github.com/Fuku-Taka/free_merge

■ Basic認証
ID：admin
Pass：add5

■ テスト用アカウント
◯ 購入者用
メールアドレス：wawa@wawa
パスワード：aaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：1/29
セキュリティカード：000

◯ 出品者用
メールアドレス：bbb@bbb
パスワード：bbbbbbb

**Comment by sho0127** [comment]
最終課題Cチームさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
「topページに商品一覧が表示されていない（ランダムピックアップのみになっている）」
「商品編集ページで戻るボタンを押しても反応しない」
修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by sho0127** [comment]
最終課題Cチームさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
